// <auto-generated />
using System;
using DemoSalesApp.DLL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoSalesApp.DLL.Migrations
{
    /// <summary>
    /// The data context model snapshot.
    /// </summary>
    /// <seealso cref="Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot" />
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        /// <summary>
        /// Called lazily by <see cref="P:Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.Model" /> to build the model snapshot
        /// the first time it is requested.
        /// </summary>
        /// <param name="modelBuilder">The <see cref="T:Microsoft.EntityFrameworkCore.ModelBuilder" /> to use to build the model.</param>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:dbo.SaleEvent_seq", "'SaleEvent_seq', 'dbo', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoSalesApp.Models.Article", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleNumber");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DemoSalesApp.Models.SaleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.SaleEvent_seq");

                    b.Property<string>("ArticleSoldNumber")
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("ArticleSoldPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleSoldNumber");

                    b.ToTable("SaleEvents");
                });

            modelBuilder.Entity("DemoSalesApp.Models.SaleEvent", b =>
                {
                    b.HasOne("DemoSalesApp.Models.Article", "ArticleSold")
                        .WithMany()
                        .HasForeignKey("ArticleSoldNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
